from pptx.enum.base import BaseEnum

class PP_ACTION_TYPE(BaseEnum):
    END_SHOW: "PP_ACTION_TYPE"
    FIRST_SLIDE: "PP_ACTION_TYPE"
    HYPERLINK: "PP_ACTION_TYPE"
    LAST_SLIDE: "PP_ACTION_TYPE"
    LAST_SLIDE_VIEWED: "PP_ACTION_TYPE"
    NAMED_SLIDE: "PP_ACTION_TYPE"
    NAMED_SLIDE_SHOW: "PP_ACTION_TYPE"
    NEXT_SLIDE: "PP_ACTION_TYPE"
    NONE: "PP_ACTION_TYPE"
    OPEN_FILE: "PP_ACTION_TYPE"
    OLE_VERB: "PP_ACTION_TYPE"
    PLAY: "PP_ACTION_TYPE"
    PREVIOUS_SLIDE: "PP_ACTION_TYPE"
    RUN_MACRO: "PP_ACTION_TYPE"
    RUN_PROGRAM: "PP_ACTION_TYPE"

PP_ACTION: PP_ACTION_TYPE
