from pptx.enum.base import BaseEnum, BaseXmlEnum

class MSO_AUTO_SIZE(BaseEnum):
    NONE: "MSO_AUTO_SIZE"
    SHAPE_TO_FIT_TEXT: "MSO_AUTO_SIZE"
    TEXT_TO_FIT_SHAPE: "MSO_AUTO_SIZE"
    MIXED: "MSO_AUTO_SIZE"

class MSO_TEXT_UNDERLINE_TYPE(BaseXmlEnum):
    NONE: "MSO_TEXT_UNDERLINE_TYPE"
    DASH_HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DASH_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DASH_LONG_HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DASH_LONG_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOT_DASH_HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOT_DASH_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOT_DOT_DASH_HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOT_DOT_DASH_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOTTED_HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOTTED_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    DOUBLE_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    SINGLE_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    WAVY_DOUBLE_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    WAVY_HEAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    WAVY_LINE: "MSO_TEXT_UNDERLINE_TYPE"
    WORDS: "MSO_TEXT_UNDERLINE_TYPE"
    MIXED: "MSO_TEXT_UNDERLINE_TYPE"

MSO_UNDERLINE: MSO_TEXT_UNDERLINE_TYPE

class MSO_VERTICAL_ANCHOR(BaseXmlEnum):
    TOP: "MSO_VERTICAL_ANCHOR"
    MIDDLE: "MSO_VERTICAL_ANCHOR"
    BOTTOM: "MSO_VERTICAL_ANCHOR"
    MIXED: "MSO_VERTICAL_ANCHOR"

MSO_ANCHOR: MSO_VERTICAL_ANCHOR

class PP_PARAGRAPH_ALIGNMENT(BaseXmlEnum):
    CENTER: "PP_PARAGRAPH_ALIGNMENT"
    DISTRIBUTE: "PP_PARAGRAPH_ALIGNMENT"
    JUSTIFY: "PP_PARAGRAPH_ALIGNMENT"
    JUSTIFY_LOW: "PP_PARAGRAPH_ALIGNMENT"
    LEFT: "PP_PARAGRAPH_ALIGNMENT"
    RIGHT: "PP_PARAGRAPH_ALIGNMENT"
    THAI_DISTRIBUTE: "PP_PARAGRAPH_ALIGNMENT"
    MIXED: "PP_PARAGRAPH_ALIGNMENT"

PP_ALIGN: PP_PARAGRAPH_ALIGNMENT
