from typing import Optional, Type

class PackURI(str):
    def __new__(cls: Type[PackURI], pack_uri_str: str) -> "PackURI": ...
    @staticmethod
    def from_rel_ref(baseURI: str, relative_ref: str) -> "PackURI": ...
    @property
    def baseURI(self) -> str: ...
    @property
    def ext(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def idx(self) -> Optional[int]: ...
    @property
    def membername(self) -> str: ...
    def relative_ref(self, baseURI: str) -> str: ...
    @property
    def rels_uri(self) -> "PackURI": ...

PACKAGE_URI: PackURI
CONTENT_TYPES_URI: PackURI
