from typing import Any, TypeVar

T = TypeVar("T")

class CaseInsensitiveDict(dict):
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> T: ...
    def __setitem__(self, key: str, value: T) -> None: ...
